### ISSUE TITLE
PanelDue 5 no longer available from Filastruder; substitute PanelDue 5i

### ISSUE THREAD

**Issue by SteveDallas** [railcore/parts#15]
Affects: 300 ZL and 300 ZLT BOMs.

The non-integrated PanelDue and 5" display combination is no longer available from Filastruder, so the BOM link doesn't get you to the right part.

This link is for the PanelDue 5i with a 1 meter 4 pin cable:
https://www.filastruder.com/products/paneldue-5i?variant=12524929876039

The price is $89.99

**Comment by dandancheeseandham** [comment]
@SteveDallas Thank you. Done!
